name: flexpay
description: "A flexpay app"

publish_to: 'none' 
version: 2.0.67+97

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.2.11
  get: ^4.6.1
  flutter_otp_text_field: ^1.1.0+2
  iconsax: ^0.0.8
  http: ^1.2.2
  intl: ^0.20.2
  percent_indicator: ^4.2.2
  session_manager: ^0.0.4
  video_player: ^2.5.1
  flutter_swiper_view: ^1.1.8
  swipe_deck: ^1.0.2
  dio: ^5.7.0
  dio_adapter: ^2.1.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_charts: ^29.1.39
  animate_do: ^4.2.0
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  overlay_support: ^2.1.0
  flutter_spinkit: ^5.2.1
  top_snackbar_flutter: ^3.2.0
  lottie: ^3.3.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.1.0
  device_preview: ^1.2.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  upgrader: ^11.5.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  webview_flutter: ^4.13.0
  flutter_card_swiper: ^7.1.0
  flutter_typeahead: ^5.2.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.4
  firebase_performance: ^0.11.1+2
  device_info_plus: ^12.1.0
  flutter_local_notifications: ^19.5.0
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.6
  bloc_test: ^10.0.0
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/flexpaylogo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icon/flexpaylogo.png"
  adaptive_icon_background: "#ffffff"
  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icon/
    - assets/icon/logos/logo.png
    - assets/merchants/
    - assets/merchantspageimg/
    - assets/images/auth_images/
    - assets/images/bookings_imgs/
    - assets/images/flags/
    - assets/images/goals_imgs/
    - assets/images/notification_imgs/
    - assets/images/payment_platform/
    - assets/images/home_images/
    - .env 